{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "469844d3",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.sql import SparkSession\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "import pandas as pd\n",
    "import boto3\n",
    "from io import BytesIO\n",
    "\n",
    "spark = SparkSession.builder.appName(\"SQLQueryVisualization\").getOrCreate()\n",
    "\n",
    "s3_path = \"s3://outputfinall/finalcsv/run-1701832521370-part-r-00000 (1).csv\"\n",
    "\n",
    "df = spark.read.option(\"header\", \"true\").csv(s3_path)\n",
    "\n",
    "df.createOrReplaceTempView(\"my_table\")\n",
    "\n",
    "query1 = \"\"\"\n",
    "SELECT \n",
    "    Sex,\n",
    "    AVG(Age) AS AvgAge\n",
    "FROM my_table\n",
    "GROUP BY Sex\n",
    "\"\"\"\n",
    "\n",
    "query2 = \"\"\"\n",
    "SELECT \n",
    "    PhysActivity,\n",
    "    AVG(HeartDiseaseorAttack) AS AvgHeartDisease\n",
    "FROM my_table\n",
    "GROUP BY PhysActivity\n",
    "\"\"\"\n",
    "\n",
    "result1_df = spark.sql(query1)\n",
    "result2_df = spark.sql(query2)\n",
    "\n",
    "result1_pandas = result1_df.toPandas()\n",
    "result2_pandas = result2_df.toPandas()\n",
    "\n",
    "fig, axes = plt.subplots(nrows=1, ncols=2, figsize=(15, 5))\n",
    "fig.suptitle('SQL Query Visualization', fontsize=16)\n",
    "\n",
    "sns.barplot(x=\"Sex\", y=\"AvgAge\", data=result1_pandas, ax=axes[0])\n",
    "axes[0].set_title('Average Age by Sex')\n",
    "\n",
    "sns.barplot(x=\"PhysActivity\", y=\"AvgHeartDisease\", data=result2_pandas, ax=axes[1])\n",
    "axes[1].set_title('Average Heart Disease by Physical Activity')\n",
    "\n",
    "buffer_visualization = BytesIO()\n",
    "plt.savefig(buffer_visualization, format='png')\n",
    "buffer_visualization.seek(0)\n",
    "\n",
    "s3_bucket = \"cretee\"\n",
    "s3_visualization_key = \"store/sql_query_visualization.png\"\n",
    "\n",
    "s3 = boto3.client(\"s3\")\n",
    "s3.upload_fileobj(buffer_visualization, s3_bucket, s3_visualization_key)\n",
    "\n",
    "plt.show()\n",
    "\n",
    "spark.stop()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
